### ISSUE TITLE
Stuck on PLANNING

### ISSUE THREAD

**Issue by lapo-luchini** [zrepl/zrepl#791]
It happens to me more often lately that the process is stuck on some PLANNING phases:
![image](https://github.com/zrepl/zrepl/assets/420454/d8d1d094-071e-4fa1-b86a-7122b785f5c9)
If I do signal reset, and then wake-up, it starts again and sometimes it works, while other times after a while it gets stuck again (on random filesystems apparently, not always the same).
How can I help debug this?
And, as a safeguard, would it be possible to have a watchdog… like, if a phase hasn't ended by 10 minutes, abort it and consider it failed for this round?

**Comment by A1bi** [comment]
I am also experiencing this frequently now on FreeBSD 14.0. Pretty sure it only started recently, maybe with the update to FreeBSD 14.0. I also haven't seen it on my Linux based systems yet, so it may be related to that FreeBSD update.

**Comment by kapsel** [comment]
We are also seeing this issue, we are on FreeBSD 14.0. Restarting zrepl works.

**Comment by lapo-luchini** [comment]
This might be "better" than a full restart, as a work-around:
`sudo zrepl signal reset <name>`

**Comment by dsh2dsh** [comment]
JFYI, in my [fork](https://github.com/dsh2dsh/zrepl) I implemented a timeout and it helped me a lot. Also, using a cron spec I configured some jobs with same ZFS datasets, so zrepl fires them at different time and they are not intersecting.

**Comment by lapo-luchini** [comment]
Wow @dsh2dsh there's a lot of work in your fork! Why it doesn't show up on github.com as a fork?
(that makes it more difficult to inspect the diff between the two projects)
@problame any chance any of that work will be included?
Would be nice to have a new official release. :)

**Comment by lapo-luchini** [comment]
At least for me this seems to be related to the number of parallel seize estimation steps, it no longer happened to me since I did this:

```yaml
  replication:
    concurrency:
      size_estimates: 1
      #size_estimates: 4
      steps: 10
```

**Comment by A1bi** [comment]
The issue remains with FreeBSD 14.1. I have to reset zrepl on a daily basis.

**Comment by problame** [comment]
Hey, sorry for the very delayed reply on this issue.

@dsh2dsh you have advertised your fork here and in https://github.com/zrepl/zrepl/issues/824 --- do you have a concrete fix for this specific issue? 

I don't have time to repro the problem (not using FreeBSD anymore :( ).

**Comment by problame** [comment]
@lapo-luchini , since it's not specified in the issue description: are you on FreeBSD and if yes on which version?

**Comment by lapo-luchini** [comment]
Oh, sorry, yes: I'm on FreeBSD 14.1

**Comment by silenius** [comment]
I'm having the same issue, it seems related to FreeBSD 14.x (it never happened on 13.x)

**Comment by silenius** [comment]
to be confirmed, but I recently upgraded to 14.2-RELEASE and this problem has not occurred again until now.

**Comment by A1bi** [comment]
> to be confirmed, but I recently upgraded to 14.2-RELEASE and this problem has not occurred again until now.

Unfortunately I cannot confirm this. The issue still constantly occurs on my servers after the update to FreeBSD 14.2.

**Comment by silenius** [comment]
yeah.. I spoke too fast, it still happens on 14.2-RELEASE too

**Comment by Schueni1** [comment]
Also with FreeBSD 14.3-RELEASE this issue persists. 
Switching to the fork from dsh2dsh did not help either.

My current work around is to monitor zrepl with prometheus and use alertmanager with a webhook to initiate a zrepl reset and zrepl wakeup, when it gets stuck.

alertmanager.yaml
```
receivers:
- name: 'zreplZeus'
  webhook_configs:
  - url: 'http://marvin.local:9000/hooks/resetAndWakeupZreplZeus'
    send_resolved: false
```
alert_rules.yaml
```
  - alert: zreplResetZeus
    expr: time() - zrepl_replication_last_successful{zrepl_job="pull_from_zeus"} > 1080
    for: 5m
    labels:
      severity: "critical"
      zrepl: "zeus"
    annotations:
      summary: "Endpoint {{ $labels.instance }} down"
      description: "Zrepl zeus is stuck"
```
webhook.yaml
(the trigger-rule only allows the monitoring prometheus server to restart zrepl with the webhook)
```
---
- id: resetAndWakeupZreplZeus
  execute-command: "/var/webhook/zreplZeus"
  command-working-directory: "/var/webhook"
  trigger-rule:
    match:
      type: "ip-whitelist"
      ip-range: "192.168.12.102/32"
```
the script that restarts zrepl
```
#!/bin/sh
/usr/local/bin/zrepl signal reset pull_from_zeus && /usr/local/bin/zrepl signal wakeup pull_from_zeus
```

**Comment by A1bi** [comment]
I know it’s contrary to what @Schueni1 wrote, but I am slowly getting optimistic that this issue no longer occurs with FreeBSD 14.3. After updating both source and target I haven’t experienced it in a month. It used to happen almost daily before.
